name: toastio_example
description: Example app for toastio.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  toastio:
    path: ..

flutter:
  uses-material-design: true
